[project]
name = "agentcore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "strands-agents>=1.36.0",
    "strands-agents-tools>=0.5.0",
    "bedrock-agentcore>=1.6.3",
    "bedrock-agentcore-starter-toolkit>=0.3.5",
    "streamlit>=1.56.0",
]

[tool.setuptools]
py-modules = ["main"]
